apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ${{ values.name }}
  namespace: ${{ values.namespace }}
  labels:
    app: ${{ values.name }}
    release: kube-prometheus-stack   # must match Prometheus Operator's serviceMonitorSelector
spec:
  selector:
    matchLabels:
      app: ${{ values.name }}
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
      - ${{ values.namespace }}
